# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: Streaming Integration Documentation
site_description: Documentation for WSO2 Enterprise Integrator
site_author: WSO2
site_url: https://wso2.com/integration/

# Repository
repo_name: wso2/docs-ei
repo_url: https://github.com/wso2/docs-ei
edit_uri: https://github.com/wso2/docs-is/edit/master/en/docs/

# Copyright
copyright: WSO2 Enterprise Integrator - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'

# Navigation
nav:
  - 'Home': index.md
  - 'Overview':
      - 'Overview': 'overview/overview.md'
      - 'Architecture': 'overview/architecture.md'
      - 'About this Release': 'overview/about_this_release.md'
  - 'Quick Start Guide':
    - 'Quick Start Guide': quick-start-guide/quick-start-guide.md
  - 'Concepts':
      - 'Concepts': 'concepts.md'
  - 'Installation Guide':
    - 'Installing the Product':
      - 'Installing the Streaming Integrator Using Docker': 'setup/installing-si-using-docker.md'
      - 'Installing the Streaming Integrator Using Docker Compose': 'setup/installing-si-using-docker-compose.md'
      - 'Installing the Streaming Integrator Using Ansible': 'setup/installing-si-using-ansible.md'
      - 'Installing the Streaming Integrator Using Kubernetes': 'setup/installing-si-using-kubernetes.md'
      - 'Installing the Streaming Integrator Using Vagrant': 'setup/installing-si-using-vagrant.md'
      - 'Installing the Streaming Integrator Using Puppet': 'setup/installing-si-using-puppet.md'
      - 'Installing the Streaming Integrator Using Helm': 'setup/installing-si-using-helm.md'
      - 'Installing the Streaming Integrator Using AWS Cloud Formation': 'setup/installing-si-using-aws-cloud-formation.md'
      - 'Installing the Streaming Integrator Using Apt': 'setup/installing-si-using-apt.md'
      - 'Installing the Streaming Integrator Using Yum': 'setup/installing-si-using-yum.md'
      - 'Installing the Streaming Integrator Using Brew': 'setup/installing-si-using-brew.md'
    - 'Deploying Streaming Integrator Profile':
      - 'Deploying the Streaming Integrator Profile as a Minimum HA cluster': 'setup/deploying-si-as-minimum-ha-cluster.md'
    - 'Setting up Databases':
      - 'Configuring Datasources': 'configuring-Datasources.md'
      - 'Setting up Physical Databases': 'setting-up-physical-databases.md'
  - 'Developer Experience':
    - 'Streaming Integrator Studio Overview': 'develop/streaming-integrator-studio-overview.md'
    - 'Designing Siddhi Applications':
      - 'Working with the Source View': 'develop/working-with-source-view.md'
      - 'Working with the Design View': 'develop/working-with-design-view.md'
    - 'Testing Siddhi Applications':
      - 'Testing a Siddhi Application': 'develop/testing-a-siddhi-application.md'
      - 'Simulating Events': 'develop/simulating-events.md'
    - 'Debugging Siddhi Applications': 'develop/debugging_siddhi_applications.md'
    - 'Exporting Siddhi Files':
      - 'Exporting a Single Siddhi File': 'develop/exporting-a-single-siddhi-file.md'
      - 'Exporting Siddhi Files as Docker Artifacts': 'develop/exporting-siddhi-files-as-docker-artifacts.md'
  - 'Use Cases':
    - 'Examples':
      - 'Performing Real-time ETL with MySQL': 'examples/performing-real-time-etl-with-mysql.md'
      - 'Performing Real-time ETL with Files': 'examples/performing-real-time-etl-with-files.md'
      - 'Working with Kafka': 'examples/working-with-kafka.md'
      - 'Working with NATS': 'examples/working-with-nats.md'
      - 'Transforming JSON Messages': 'examples/transforming-json-messages.md'
      - 'Transforming XML Messages': 'examples/transforming-xml-messages.md'
      - 'Integrating Databases to Data Flows': 'examples/integrating-databases-to-data-flows.md'
      - 'Exposing Processed Data as API': 'examples/exposing-processed-data-as-api.md'
      - 'Triggering Integrations via Micro Integrator': 'examples/triggering-integrations-via-micro-integrator.md'
      - 'Analyzing Data and Deriving Insights': 'examples/analyzing-data-and-deriving-insights.md'
      - 'Performing Reliable Data Integration (Error Streams)': 'examples/reliable-data-integration.md'
      - 'Summarizing and Aggregating Data in Real Time': 'examples/summarizing-and-aggregating-data.md'
    - 'Guides':
      - 'Consuming Data': 'guides/collecting-events.md'
      - 'Transforming Data': 'guides/transforming-data.md'
      - 'Enriching Data': 'guides/enriching-data.md'
      - 'Cleansing Data': 'guides/cleansing-data.md'
      - 'Correlating Data': 'guides/complex-Event-processing.md'
      - 'Summarizing Data': 'guides/incremental-Analysis.md'
      - 'Triggering Integration Flows': 'guides/triggering-integration-flows.md'
  - 'Admin Guide':
    - 'Configuring the Streaming Integration Profile': 'admin/configure-si-profile.md'
    - 'Working with Siddhi Connectors':
      - 'Downloading and Installing Siddhi Connectors': 'admin/downloading-and-Installing-Siddhi-Extensions.md'
      - 'Writing Custom Siddhi Extensions': 'admin/writing-Custom-Siddhi-Extensions.md'
      - 'Configuring System Parameters for Siddhi Extensions': 'admin/configuring-System-Parameters-for-Siddhi-Extensions.md'
    - 'Creating Business Rules Templates': 'admin/creating-business-rules-templates.md'
    - 'Monitoring the Streaming Integrator': 'admin/monitoring-the streaming-integrator'
    - 'General Data Protection Regulations': 'admin/general-data-protection-regulations.md'
    - 'Supporting Different Transports': 'admin/supporting-Different-Transports.md'
    - 'User Management': 'admin/user-Management.md'
    - 'Protecting Sensitive Data via the Secure Vault': 'admin/protecting-sensitive-data-via-the-secure-vault.md'
    - 'Adding Third Party Non OSGi Library': 'admin/adding-Third-Party-Non-OSGi-Libraries.md'
  - 'Reference Guide':
    - 'Streaming Integration REST API Guide': 'ref/si-rest-api-guide.md'
    - 'Performance Analysis Results': 'ref/performance-analysis-results.md'
    - 'Configuring Default Ports': 'ref/configuring-Default-Ports.md'
    - 'Working with Data Providers': 'ref/working-with-Data-Providers.md'
    - 'Streaming Integration Profiles': 'ref/wSO2-Stream-Processor-Profiles.md'
  - 'FAQ':
    - 'FAQ': faq/fAQ.md
  - '': page-not-found.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 7.0.0