# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Enterprise Integrator Documentation
site_description: Documentation for WSO2 Enterprise Integrator
site_author: WSO2
site_url: https://wso2.com/integration/

# Repository
repo_name: wso2/docs-ei
repo_url: https://github.com/wso2/docs-ei
edit_uri: https://github.com/wso2/docs-ei/edit/7.0.0/en/streaming-integrator/docs/

# Copyright
copyright: WSO2 Enterprise Integrator - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'

# Navigation
nav:
  - 'Home': index.md
  - 'Overview':
      - 'Introduction': 'overview/overview.md'
      - 'Architecture': 'overview/architecture.md'
      - 'About this Release': 'overview/about_this_release.md'
  - 'Quick Start Guide':
    - 'Getting Started': 'quick-start-guide/getting-started-with-si.md'
    - 'Quick Start Guide 101': 'quick-start-guide/quick-start-guide-101.md'
    - 'Getting SI Running with MI in 5 Minutes': 'quick-start-guide/hello-world-with-mi.md'
    - 'Getting SI Running with Docker in 5 Minutes': 'quick-start-guide/hello-world-with-docker.md'
    - 'Getting SI Running with Kubernetes in 5 Minutes': 'quick-start-guide/hello-world-with-kubernetes.md'
  - 'Concepts':
      - 'Concepts': 'concepts/concepts.md'
  - 'Setup and Install':
    - 'Installing the Product':
      - 'Install in a VM': 'setup/installing-si-in-vm.md'
      - 'Installing in Docker': 'setup/installing-si-using-docker.md'
      - 'Installing in Kubernetes': 'setup/installing-si-using-kubernetes.md'
    - 'Deploying Streaming Integrator':
      - 'Single Deployment': 'setup/deploying-si-as-a-single-deployment.md'
      - 'Minimum HA Cluster': 'setup/deploying-si-as-minimum-ha-cluster.md'
      - 'Scalable Cluster': 'setup/deploying-si-as-a-scalable-cluster.md'
    - 'Setting up Databases':
      - 'Configuring Datasources': 'setup/configuring-data-sources.md'
      - 'Setting up Physical Databases': 'setting-up-physical-databases.md'
  - 'Develop':
    - 'Streaming Integrator Tooling':
      - 'Streaming Integrator Tooling Overview': 'develop/streaming-integrator-studio-overview.md'
      - 'Working with the Design View': 'develop/working-with-the-Design-View.md'
    - 'Creating Siddhi Applications': 'develop/creating-a-Siddhi-Application.md'
    - 'Testing a Siddhi Application': 'develop/testing-a-Siddhi-Application.md'
    - 'Debugging Siddhi Applications': 'develop/debugging_siddhi_applications.md'
    - 'Exporting Siddhi Files': 'develop/exporting-Siddhi-Files.md'
  - 'Use Cases':
    - 'Guides':
      - 'Consuming Data': 'guides/consuming-messages.md'
      - 'Transforming Data': 'guides/transforming-data.md'
      - 'Enriching Data': 'guides/enriching-data.md'
      - 'Cleansing Data': 'guides/cleansing-data.md'
      - 'Correlating Data': 'guides/correlating-events.md'
      - 'Summarizing Data': 'guides/summarizing-data.md'
      - 'Integrating Stores': 'guides/storage-integration.md'
      - 'Publishing Data': 'guides/publishing-data.md'
      - 'Triggering Integration Flows': 'guides/triggering-integration-flows.md'
    - 'Tutorials':
      - 'Performing Real-time ETL with MySQL': 'examples/performing-real-time-etl-with-mysql.md'
      - 'Performing Real-time ETL with Files': 'examples/performing-real-time-etl-with-files.md'
      - 'Working with Kafka': 'examples/working-with-kafka.md'
      - 'Transforming XML Messages': 'examples/transforming-xml-messages.md'
      - 'Exposing Processed Data as API': 'examples/exposing-processed-data-as-api.md'
      - 'Triggering Integrations via Micro Integrator': 'examples/triggering-integrations-via-micro-integrator.md'

  - 'Administration':
    - 'Working with Siddhi Connectors':
      - 'Downloading and Installing Siddhi Connectors': 'admin/downloading-and-Installing-Siddhi-Extensions.md'
      - 'Writing Custom Siddhi Extensions': 'admin/writing-Custom-Siddhi-Extensions.md'
      - 'Configuring System Parameters for Siddhi Extensions': 'admin/configuring-System-Parameters-for-Siddhi-Extensions.md'
    - 'Working with Business Rules': 'admin/creating-business-rules-templates.md'
    - 'Monitoring the Streaming Integrator': 'admin/monitoring-the-streaming-integrator'
    - 'General Data Protection Regulations': 'admin/general-data-protection-regulations.md'
    - 'Supporting Different Transports': 'admin/supporting-different-transports.md'
    - 'User Management': 'admin/user-management.md'
    - 'Protecting Sensitive Data via the Secure Vault': 'admin/protecting-sensitive-data-via-the-secure-vault.md'
    - 'Adding Third Party Non OSGi Library': 'admin/adding-third-party-non-osgi-libraries.md'
  - 'References':
    - 'Streaming Integration REST API Guide': 'ref/si-rest-api-guide.md'
    - 'Performance Analysis Results': 'ref/performance-analysis-results.md'
    - 'Configuring Default Ports': 'ref/configuring-default-ports.md'
  - 'FAQ':
    - 'FAQ': faq/fAQ.md
  - '': page-not-found.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 7.0.0